---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
library(knitr)
library(ggplot2)
library(dplyr)
library(plyr)
```



```{r}
temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip", temp, mode="wb")
unzip(temp, "activity.csv")
dataset <- read.csv("activity.csv",header=T)
unlink(temp)
```

## What is mean total number of steps taken per day?

```{r}
totalstepsperday <- aggregate(steps ~ date, data = dataset, FUN = sum, na.rm = TRUE)
totalstepsperday
```


```{r}

# converting dates to Y-M-D format
dataset$date <- as.Date(dataset$date, "%Y-%m-%d")

png("TotalStepsPlot.png",width=480,height=480)
hist(totalstepsperday$steps, 
    main="Total Steps per Day", 
    xlab="Number of Steps per Day", 
    ylab = "Interval",
    col="blue",
    breaks=60)

dev.off()
```


## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
